### PR TITLE
Added function scope test to python

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — APPROVED** [review]
Nice. Do we want to remove corresponding recorded tests? Seems redundant to have recorded and scope testing the same thing

**Comment by AndreasArvidsson** [comment]
Maybe?

**Comment by pokey** [comment]
Why wouldn't we?

**Comment by AndreasArvidsson** [comment]
I was just thinking that our tests might test different syntax patterns, but I'm not against removing them.

**Comment by pokey** [comment]
I think the idea should be for our scope tests to cover what our recorded tests used to cover. Maybe we should migrate one scope-language pair at a time? Ie for this PR we look at what recorded tests we have for Python lambda and function, add scope tests that are at least as comprehensive, and remove the recorded tests?

It's a bit more work, but would be nice to get our test suite a bit more principled

**Comment by AndreasArvidsson** [comment]
Sounds good. Tests updated.

**Review by pokey — APPROVED** [review]
🚀

**Pull request merged**
