### PR TITLE
Added more information to command history analyzer

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Added some more aggregated information about your command history

```
# Totals

Command count: 53863
Days usage: 166
Average commands / day: 324
Commands with hats: 8592 (16%)
```

## Checklist

- [/] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
i haven't read the PR, but that percentage looks off to me 😄

**Comment by AndreasArvidsson** [comment]
> i haven't read the PR, but that percentage looks off to me 😄

Oh I forgot to multiply with 100 of course :D

**Comment by AndreasArvidsson** [comment]
fixed

**Review by pokey — APPROVED** [review]
Made some tweaks; merge if happy

**Comment by AndreasArvidsson** [comment]
I'm not happy! :D
You're now incrementing `decoratedMarkCommandCount` for every decorated target. The reason I had it the way it was before is that I only want to increment it per command as the name suggests.

**Pull request merged**
