### PR TITLE
Documentation for row, up, down

### LINKED ISSUE #706: Add up, down and row scopes to docs

### PR DESCRIPTION
**Pull request by brollin**
Closes #706. Didn't touch the cheatsheet for now.

Maybe these special marks could belong in their own section somehow? I wasn't sure so I just tacked them onto the preexisting marks section.

### CODE REVIEW

**Review by pokey — DISMISSED** [review]
Made some minor tweaks; otherwise looks good to me!  Lmk if you're happy with my tweaks.  Also cc/ @AndreasArvidsson who wrote / uses (used?) these marks

**Comment by AndreasArvidsson** [comment]
Looks good to me. The only thing we might want to add is that the relative line numbers are relative to your primary selection only. ie they align with relative line numbers in vscode.

**Comment by brollin** [comment]
Cool, hopefully captured that effectively in the last change. Feel free to tweak of course.

**Comment by AndreasArvidsson** [comment]
I'm happy :)

**Review by pokey — APPROVED** [review]
looks good thanks!

**Pull request merged**
