### PR TITLE
Extend ide capabilities

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
When the ide don't have capabilities/own implementation of `indentLine`, `outdentLine` and `insertLineAfter` fallback to doing an editor edit instead. This makes it so that in a non code editor environment like the web browser we still get these three actions implemented.

Ideally we would test this, but that would involve running tests with mocked capabilities. I think that is a lot of work?

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
I agree. The test are not passing, but I think this direction is nice.

**Comment by AndreasArvidsson** [comment]
After another tweak now the tests are passing

**Comment by pokey** [comment]
maybe it makes sense to pull in the in-memory text document and text editor from your talon js PR to use for testing here? You could just directly instantiate this action and run it

**Comment by pokey** [comment]
update from meet-up: split this PR to include only the "pour" piece, as that is simple enough to not really need tests

**Comment by AndreasArvidsson** [comment]
Okay this is now just pour. Here is the pr for indent
https://github.com/cursorless-dev/cursorless/pull/2518

**Review by pokey — APPROVED** [review]

**Pull request merged**
