### PR TITLE
add `cursorless.private.logQuickActions` internal command

### PR DESCRIPTION
**Pull request by pokey**
Useful for development as we add new Cursorless actions based on VSCode quick actions. We should prob put this in https://github.com/cursorless-dev/cursorless/issues/1775 once that exists, but until then, seems harmless here

## Checklist

- [-] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Comment by AndreasArvidsson** [comment]
I don't quite follow the purpose of this. Why not just called the quick fix command and get the ui with available actions instead of printing them in the log?

**Comment by pokey** [comment]
I print the ids and titles in the log. I can then use the id when automatically triggering a quick action. The things in the quick fix popup don't have ids. Unless I'm missing something?

**Comment by AndreasArvidsson** [comment]
Is it the kind you are after? Because I got confused that you can actually pass the kind as an argument in.

**Comment by AndreasArvidsson** [comment]
If you print the command instead we could just call that directly and don't have to bother with the quick fix menu?

**Comment by pokey** [comment]
> Is it the kind you are after? Because I got confused that you can actually pass the kind as an argument in.

I don't actually pass that in. It's optional. You can pass that if you want to pass a general kind and see all the specific sub-kinds. But I could prob just drop that arg if it's confusing

**Comment by pokey** [comment]
> If we print the command instead we could just call that directly and possibly don't have to bother with the quick fix menu?

Is there a command? Didn't realise that was returned. I could just print exactly what comes back; I believe the filtering was from when I was trying to show it in a notification in an earlier draft and then just switched to debug console

**Comment by AndreasArvidsson** [comment]
> > Is it the kind you are after? Because I got confused that you can actually pass the kind as an argument in.
> 
> I don't actually pass that in. It's optional. You can pass that if you want to pass a general kind and see all the specific sub-kinds. But I could prob just drop that arg if it's confusing

Got it. Not that obvious that you can pass in a general/prefix. I can a thought that why would you pass the exact kind to then have just that printed back. Maybe the comment can be updated to better reflect this?

> > If we print the command instead we could just call that directly and possibly don't have to bother with the quick fix menu?
> 
> Is there a command? Didn't realise that was returned. I could just print exactly what comes back; I believe the filtering was from when I was trying to show it in a notification in an earlier draft and then just switched to debug console

Yes The code action class has an optional command field. Probably best to just print the entire return value. 


I do wonder if we should name this command something else; `showQuickAction` kinda sounds like it will show the quick pick ui. `logQuickActions` or something like that would make it more obvious what it's actually doing.

**Comment by pokey** [comment]
> Got it. Not that obvious that you can pass in a general/prefix. I can a thought that why would you pass the exact kind to then have just that printed back. Maybe the comment can be updated to better reflect this?

Done

> Yes The code action class has an optional command field. Probably best to just print the entire return value.

I just tried that, and the command field is always either not present, or points to an internal command. For example:

```json
{
  "title": "Extract to inner function in function 'logQuickActions'",
  "kind": {
    "value": "refactor.extract.function"
  },
  "command": {
    "title": "Extract to inner function in function 'logQuickActions'",
    "command": "_typescript.didApplyRefactoring",
    "arguments": [
      {
        "action": "function_scope_0"
      }
    ]
  },
  "isPreferred": false
}
```

 I would be inclined to keep it the way it is, where I retain only the useful information (`kind.value`, `title` and `isPreferred`)

> I do wonder if we should name this command something else; `showQuickActions` kinda sounds like it will show the quick pick ui. `logQuickActions` or something like that would make it more obvious what it's actually doing.

Done

**Review by AndreasArvidsson — APPROVED** [review]

**Pull request merged**
