### PR TITLE
experiment with hatdocs / txtar

### PR DESCRIPTION
**Pull request by josharian**
For voice discussion. Lots of important caveats and explaining required.

interesting fixtures:

* packages/cursorless-vscode-e2e/src/suite/fixtures/recorded//everyRange/clearEveryFunkNameFinePastBlueDrum.yml
* packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/languages/scss/moveFirstWordZipBeforeFineTakeFine.yml
* packages/cursorless-vscode-e2e/src/suite/fixtures/recorded/actions/giveEqualsPastColon.yml

```go
type RangeDoc struct {
	Content string
	Ranges  []NamedRangeSet // "hats", "selections", "that", etc.
}

type NamedRangeSet struct {
	Name   string
	Ranges []AnnotatedRange // ranges along with annotations
}

type AnnotatedRange struct {
	Annotation    string
	AnnotationEnd int // how many chars into the range should the annotatin end (e.g. for hats); zero means "don't care", which we will interpret for now as "center"
	Range         Range
	Direction     Direction
}

type Range struct {
	Start Position `yaml:"start,flow"`
	End   Position `yaml:"end,flow"`
}

type Direction int

const (
	DirectionNone Direction = iota
	DirectionStart
	DirectionEnd
)
```

```
range
!
#
[]
[-]
[--]

directed range
!
>
<
[>
<]
[->
<-]
```

```
--- raw notes ---
- Q: primary cursor: how? range? use a hat ref? can't quite cram that last single bool in there :/
- Q: visible vs invisible contents using > vs <?
- Q: how to sync with scope tests, subtle differences due to different needs
- Q: unicode? tabs?

txtar: way to combine hatdoc + metadata for other purposes
- hat tests: hats, tokens (set of ranges), split editors, multi-stage assignment (either file naming conventinos or config at top)
- test fixtures: extract initial/final docs and some ranges (maybe now can run some of these editor-free?!)
- txtar makes it easier to update just part, do diffs, do multi-step things, do multi-editor things, etc.

# problems

currently losing some thatMark (etc) metadata: reversed, explicit, etc.
ranges need lots more metadata (isReversed, explicit, etc) / annotations :(


# stats test

given doc + other metadata:

number of 0, 1, 2 penalty hats
nubmer of hats on first letter of word
percent of tokens with no hat
distance to nearest token with no hat

```

### CODE REVIEW

**Comment by josharian** [comment]
https://github.com/cursorless-dev/cursorless/pull/1768/commits/1ac8931cf0c6274873c61f2f97a73a8a1c4ecd86

**Comment by pokey** [comment]
Fwiw if you mark a PR as draft, as you've done, we won't merge it, and will assume it's WIP, so you don't need the big all-caps caveat in the title 😄. We also have a `to discuss` tag you can put on it which indicates it should be discussed in a meet-up

**Comment by pokey** [comment]
Also, I'm guessing you've seen https://github.com/cursorless-dev/cursorless/issues/1524, but figured I'd mention it just in case

**Comment by josharian** [comment]
> I'm guessing you've seen https://github.com/cursorless-dev/cursorless/issues/1524

This was very much inspired by #1524. Unfortunately due to different needs, they diverged in minor ways, and continue to do so. I was designing for hat tests and then got distracted by attempting to re-use for other fixtures. https://github.com/cursorless-dev/cursorless/issues/1767 is an added wrinkle I'm still pondering.

**Comment by josharian** [comment]
this is actually ready to discuss a bit now. will need voice intro, though, for sure.

**Comment by josharian** [comment]
outcome from meetup: as anticipated, the advantages of having a single uniform data format are outweighed by the disadvantages of it not being a perfect fit for any particular use case.

plan is that @pokey (and maybe @AndreasArvidsson?) are going to look through a few of the interesting fixtures in case there are any ideas they want to steal, and we will put this on ice. :)

**Pull request closed without merging**
