### PR TITLE
Add generic file watcher api

### PR DESCRIPTION
**Pull request by pokey**
- Required by https://github.com/cursorless-dev/cursorless/pull/1803
- Required by https://github.com/cursorless-dev/cursorless/pull/1663

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
> I'm not in love with the polling implementation. I would prefer if we added support for file watchers if you have a recent enough version.

Yeah I think probably not too much effort to do version check and use watcher if available. For now, this is only used for dev hot reloading, though, (ie the code doesn't even run in production), and I won't have much time to work on it for next few days as I'm travelling. Mind if we merge this so you / @josharian can have hot reloading and then I'll do quick follow-up early next week with proper watcher? 

Fwiw this is the exact same mechanism we use in production for snippet reloading, and it's quite low resource utilisation as it's just a stat

**Comment by josharian** [comment]
> Mind if we merge this so you / @josharian can have hot reloading and then I'll do quick follow-up early next week with proper watcher?

yes please!

**Comment by josharian** [comment]
tbh, for dev only, i don't see that it's worth the effort to switch from polling, if polling is already built.

**Comment by pokey** [comment]
We will be using it for the tree-view next, so I'll switch before we ship that

**Comment by pokey** [comment]
You can also just rebase onto this branch while developing for now. That's what I did for my PR

**Review by AndreasArvidsson — APPROVED** [review]

**Comment by AndreasArvidsson** [comment]
How can I say no to josh? Commence the merging!

**Pull request merged**
