### PR TITLE
Pattern matching support

### PR DESCRIPTION
**Pull request by purpleP**
I’m working on pattern matching support as discussed [here](https://github.com/cursorless-dev/cursorless/issues/579#issuecomment-1161627378) and planning to add it to rust, java, c, c++, python, javascript, typescript and haskell (languages I know).

So far I don’t think cursorless even recognised new scopes. @pokey Can you point what I’m missing here?

### CODE REVIEW

**Comment by pokey** [comment]
Have you symlinked / copied cursorless-talon into your talon user directory, replacing the deployed version of cursorless?

If so, maybe try restarting talon and saying "cursorless help" to see if they're appearing in the cheatsheet?

**Comment by purpleP** [comment]
> Have you symlinked / copied cursorless-talon subdir of this branch into your talon user directory, replacing the deployed version of cursorless?
> 
> If so, maybe try restarting talon and saying "cursorless help" to see if they're appearing in the cheatsheet?

Thanks, that helped! Tell me please what do I need to add so that `chuck branch’s would remove the empty line also? Or we just delegate that to a formatter?

**Comment by purpleP** [comment]
What should we do with alternatives in patterns in Rust? I believe python and Haskell also have them.

**Comment by pokey** [comment]
Split into the following PRs:

- https://github.com/cursorless-dev/cursorless/pull/1147
- https://github.com/cursorless-dev/cursorless/pull/1148
- https://github.com/cursorless-dev/cursorless/pull/1149
- https://github.com/cursorless-dev/cursorless/pull/1150
- https://github.com/cursorless-dev/cursorless/pull/1151

**Comment by pokey** [comment]
After discussion in meet-up:

Just kidding; let's get this thing in for the languages that exist here.  more useful to at least have it functional in some places

**Pull request closed without merging**
