### PR TITLE
Don't show lines in our facet tests that are outside of the range

### PR DESCRIPTION
**Pull request by pokey**
Fixes https://github.com/cursorless-dev/cursorless/issues/2164

## Checklist

- [-] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
I think this is a win cc/ @josharian @AndreasArvidsson

**Comment by pokey** [comment]
@wenkokke this will make some of your test files shorter

**Comment by josharian** [comment]
i'm a tentative +1

**Comment by AndreasArvidsson** [comment]
I think this is an improvement. I do wonder if we also should remove empty range lines? Having those empty lines in the middle of the code block doesn't really help you with readability. Also now that we exclude lines outside of the range I'm tempted to go back to having the start range be above the code.

```
  >-------------------
0| function myFunk() {
1|
2| }
   -<
```

**Comment by pokey** [comment]
I disagree on both counts 😅. Shall we aim to discuss? I'd be inclined to merge this in the meantime as I think we all tentatively agree it's an improvement?

**Comment by AndreasArvidsson** [comment]
Ok with me

**Comment by pokey** [comment]
Sounds good. I'll merge once you give it the stamp

**Review by AndreasArvidsson — APPROVED** [review]

**Pull request merged**
