### PR TITLE
Added text insertion action to Cursorless public api

### LINKED ISSUE #1754: Expose insert action in public api
# The problem

The question of how you insert text with Cursorless comes up quite often. People often want to insert text at a position away from their current cursor position.

# The solution
There is no way we can support all different ways people want to insert text. Different languages, math formulas and so on. The list is basically infinite. If we instead just exposed a insert action the user can insert text however they want. 

```python
def cursorless_insert(destination: CursorlessDestination, text: Union[str, List[str]]):
```

## Examples

For example, this could be used as follows:

```talon
word <user.word> <user.cursorless_destination>:
    user.cursorless_insert(cursorless_destination, word)
```

Then the user would be able to say eg `"word hello after air"`

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #1754

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [x] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — APPROVED** [review]
Looks good!

**Comment by josharian** [comment]
This might be a good PR to use for the inaugural changelog note (https://github.com/cursorless-dev/cursorless/issues/1795).

**Comment by AndreasArvidsson** [comment]
Agreed. Pokey maybe we should try to discuss tomorrow were and exactly how we want these files to look and this might be the first one?

**Comment by pokey** [comment]
Sure, happy to discuss. Is there something specific from the description of #1795 that is unclear that you wanted to discuss?

**Comment by AndreasArvidsson** [comment]
For once it doesn't even say where to place the files. Should I link the pull request, the creation date and so on?

**Comment by pokey** [comment]
It provides an example of `changelog/2023-08-expanded-talon-api.md`. I would also put PR number and release date in frontmatter

**Comment by AndreasArvidsson** [comment]
I made a try here
https://github.com/cursorless-dev/cursorless/pull/1886/commits/bdbfa75e070b73d05302f543c621be45b90d8152

**Pull request merged**
