### PR TITLE
Updated source and that mark for replace action

### LINKED ISSUE #1883: Update replace action sources/that marks
Today `that` refers to the original. Switch so that `source` refers to the regional and `that` return first to the new text.

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #1883

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — APPROVED** [review]
Looks good, but worth adding a test with "to" insertion mode

**Comment by AndreasArvidsson** [comment]
That is already tested by multiple sort/reverse test. Do you want another one?

**Comment by pokey** [comment]
I'm guessing that doesn't test `source`, but I don't feel strongly; feel free to merge or add test first

**Comment by AndreasArvidsson** [comment]
You are right. Test added

**Pull request merged**
