### PR TITLE
pokey's keyboard improvements

### PR DESCRIPTION
**Pull request by josharian**
Replay of #2156, but it builds. And has tests.

- Highlight instanceReference
- Add `implicit` special target
- Add keyboard special target
- Add "and" support to keyboard
- add tests for "and"
- Add every keyboard interface
- add tests for keyboard every
- Add three funks to keyboard
- add tests for three funks
- Add paired delimiters to keyboard
- add tests for paired delimiters
- keyboard hacky attempt at pair wrap
- add pair wrap keyboard tests
- tweaks

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Comment by josharian** [comment]
Not sure how we want to juggle these for review etc. Maybe we can discuss over voice. (Probably easiest is for you to just steal whatever you want from this and incorporate into #2156?) Also, I didn't think too deeply about the new keybindings, very open to changing them.

Now that I have this building and testeed, I'll probably send a follow-up that builds atop it.

For reference, the diff from #2156 to #2159 is:

```diff
diff --git a/packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts b/packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
index 729555c9..765cff31 100644
--- a/packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
+++ b/packages/cursorless-vscode-e2e/src/suite/keyboard/basic.vscode.test.ts
@@ -7,6 +7,68 @@ import path from "path";
 import { getCursorlessRepoRoot } from "@cursorless/common";
 import { readFile } from "node:fs/promises";
 
+interface TestCase {
+  name: string;
+  initialContent: string;
+  // keySequence is the sequence of keypresses that will be sent.
+  // It can include phantom ";"s for readability.
+  // They will be not be sent.
+  keySequence: string;
+  finalContent: string;
+}
+
+const testCases: TestCase[] = [
+  {
+    name: "and",
+    initialContent: "x T y\n",
+    // change plex and yank
+    keySequence: "dx;fa;dy;c",
+    finalContent: "T",
+  },
+  {
+    name: "every",
+    initialContent: "a a\nb b\n",
+    // change every token air
+    keySequence: "da;x;st;c",
+    finalContent: "b b",
+  },
+  {
+    name: "three",
+    initialContent: "a b c d e\n",
+    // change three tokens bat
+    keySequence: "db;3;st;c",
+    finalContent: "a  e",
+  },
+  {
+    name: "three backwards",
+    initialContent: "a b c d e\n",
+    // change three tokens backwards drum
+    keySequence: "dd;-3;st;c",
+    finalContent: "a  e",
+  },
+  {
+    name: "pair parens",
+    initialContent: "a + (b + c) + d",
+    // change parens bat
+    keySequence: "db;wp;c",
+    finalContent: "a +  + d",
+  },
+  {
+    name: "pair string",
+    initialContent: 'a + "w" + b',
+    // change parens bat
+    keySequence: "dw;wj;c",
+    finalContent: "a +  + b",
+  },
+  {
+    name: "wrap",
+    initialContent: "a",
+    // round wrap air
+    keySequence: "da;aw;wp",
+    finalContent: "(a)",
+  },
+];
+
 suite("Basic keyboard test", async function () {
   endToEndTestSetup(this);
 
@@ -21,6 +83,9 @@ suite("Basic keyboard test", async function () {
   test("Don't take keyboard control on startup", () => checkKeyboardStartup());
   test("Basic keyboard test", () => basic());
   test("Run vscode command", () => vscodeCommand());
+  for (const t of testCases) {
+    test("Sequence " + t.name, () => sequence(t));
+  }
   test("Check that entering and leaving mode is no-op", () =>
     enterAndLeaveIsNoOp());
 });
@@ -65,6 +130,22 @@ async function basic() {
   assert.equal(editor.document.getText().trim(), "a");
 }
 
+/**
+ * sequence runs a test keyboard sequences.
+ */
+async function sequence(t: TestCase) {
+  const { hatTokenMap } = (await getCursorlessApi()).testHelpers!;
+
+  const editor = await openNewEditor(t.initialContent, {
+    languageId: "typescript",
+  });
+  await hatTokenMap.allocateHats();
+  editor.selection = new vscode.Selection(1, 0, 1, 0);
+  await vscode.commands.executeCommand("cursorless.keyboard.modal.modeOn");
+  await typeText(t.keySequence.replaceAll(";", ""));
+  assert.equal(editor.document.getText().trim(), t.finalContent);
+}
+
 async function vscodeCommand() {
   const { hatTokenMap } = (await getCursorlessApi()).testHelpers!;
 
diff --git a/packages/cursorless-vscode/src/extension.ts b/packages/cursorless-vscode/src/extension.ts
index 974cb297..35103c6d 100644
--- a/packages/cursorless-vscode/src/extension.ts
+++ b/packages/cursorless-vscode/src/extension.ts
@@ -49,7 +49,7 @@ import { StatusBarItem } from "./StatusBarItem";
 import { vscodeApi } from "./vscodeApi";
 import { mkdir } from "fs/promises";
 import { TestCaseRecorder } from "@cursorless/cursorless-engine";
-import storedTargetHighlighter from "./storedTargetHighlighter";
+import { storedTargetHighlighter } from "./storedTargetHighlighter";
 
 /**
  * Extension entrypoint called by VSCode on Cursorless startup.
diff --git a/packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts b/packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts
index 657bb007..f8366b8c 100644
--- a/packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts
+++ b/packages/cursorless-vscode/src/keyboard/KeyboardCommandHandler.ts
@@ -1,4 +1,4 @@
-import { ScopeType } from "@cursorless/common";
+import { ScopeType, SurroundingPairName } from "@cursorless/common";
 import * as vscode from "vscode";
 import { HatColor, HatShape } from "../ide/vscode/hatStyles.types";
 import { SimpleKeyboardActionType } from "./KeyboardActionType";
@@ -83,14 +83,14 @@ export class KeyboardCommandHandler {
   }: {
     actionName: SimpleKeyboardActionType;
   }) {
-    this.targeted.performActionOnTarget(actionName);
+    this.targeted.performSimpleActionOnTarget(actionName);
   }
 
   modifyTargetContainingScope(arg: { scopeType: ScopeType }) {
     this.targeted.modifyTargetContainingScope(arg);
   }
   performWrapActionOnTarget({ delimiter }: { delimiter: SurroundingPairName }) {
-    const [left, right] = surroundingPairsDelimiters[delimiter as any]!;
+    const [left, right] = surroundingPairsDelimiters[delimiter]!;
     this.targeted.performActionOnTarget((target) => ({
       name: "wrapWithPairedDelimiter",
       target,
diff --git a/packages/cursorless-vscode/src/keyboard/TokenTypes.ts b/packages/cursorless-vscode/src/keyboard/TokenTypes.ts
index 7dc63539..ee1db690 100644
--- a/packages/cursorless-vscode/src/keyboard/TokenTypes.ts
+++ b/packages/cursorless-vscode/src/keyboard/TokenTypes.ts
@@ -25,7 +25,8 @@ type MiscValue =
   | "makeRange"
   | "makeList"
   | "forward"
-  | "backward";
+  | "backward"
+  | "wrap"; // TODO: move wrap somewhere out of misc
 
 /**
  * Maps from token type used in parser to the type of values that the token type
@@ -53,7 +54,7 @@ export interface TokenTypeValueMap {
 
   // action config section
   simpleAction: SimpleKeyboardActionType;
-  wrap: undefined;
+  wrap: "wrap";
 
   // misc config section
   makeRange: "makeRange";
diff --git a/packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts b/packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts
index 546dce7b..65dcbd86 100644
--- a/packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts
+++ b/packages/cursorless-vscode/src/keyboard/getTokenTypeKeyMaps.ts
@@ -44,7 +44,7 @@ export function getTokenTypeKeyMaps(
       "action",
       simpleKeyboardActionNames,
     ),
-    wrap: getSingularSectionEntry("actions", "wrap"),
+    wrap: config.getTokenKeyMap("wrap", "misc", ["wrap"]),
 
     // misc config section
     makeRange: config.getTokenKeyMap("makeRange", "misc", ["makeRange"]),
@@ -60,6 +60,7 @@ export function getTokenTypeKeyMaps(
     ]),
 
     // modifier config section
+    every: config.getTokenKeyMap("every", "modifier", ["every"]),
     nextPrev: config.getTokenKeyMap("nextPrev", "modifier", ["nextPrev"]),
 
     digit: Object.fromEntries(
diff --git a/packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json b/packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
index 5e900633..22ce1498 100644
--- a/packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
+++ b/packages/cursorless-vscode/src/keyboard/keyboard-config.fixture.json
@@ -60,10 +60,13 @@
   "cursorless.experimental.keyboard.modal.keybindings.misc": {
     "fx": "combineColorAndShape",
     "fk": "makeRange",
-    "-": "backward"
+    "fa": "makeList",
+    "-": "backward",
+    "aw": "wrap"
   },
   "cursorless.experimental.keyboard.modal.keybindings.modifier": {
-    "n": "nextPrev"
+    "n": "nextPrev",
+    "x": "every"
   },
   "cursorless.experimental.keyboard.modal.keybindings.vscodeCommand": {
     "va": "editor.action.addCommentLine",
@@ -77,5 +80,21 @@
       "keepChangedSelection": true,
       "exitCursorlessMode": true
     }
+  },
+  "cursorless.experimental.keyboard.modal.keybindings.pairedDelimiter": {
+    "wl": "angleBrackets",
+    "wt": "backtickQuotes",
+    "wb": "curlyBrackets",
+    "wd": "doubleQuotes",
+    "wwd": "escapedDoubleQuotes",
+    "wwp": "escapedParentheses",
+    "wws": "escapedSquareBrackets",
+    "wwq": "escapedSingleQuotes",
+    "wp": "parentheses",
+    "wq": "singleQuotes",
+    "ws": "squareBrackets",
+    "wg": "string",
+    "wj": "any",
+    "wk": "collectionBoundary"
   }
 }
```

**Comment by josharian** [comment]
Test failures are due to forbidding TODOs. That's fine. We should indeed un-TODO them. :)

**Comment by pokey** [comment]
nice will have a look. fwiw e09b834ff2de96d45de14dae9a0829730aaa7444 is a commit that only took about 15 mins but I forgot to push. It's necessary to make the keyboard special target actually do something

**Comment by pokey** [comment]
Landed in a few smaller PRs

**Pull request closed without merging**
