### PR TITLE
Migrate Python branch scopes to fixtures

### PR DESCRIPTION
**Pull request by pokey**
Figured while I was testing https://github.com/cursorless-dev/cursorless/pull/2383 I might as well do something useful at the same time 😊

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Review by AndreasArvidsson — APPROVED** [review]

**Comment by AndreasArvidsson** [comment]
> Nice to see the reduction in lines of code here 🙌

Definitely! Really happy with this new format.

**Comment by pokey** [comment]
Actually forgot to remove the "chuck" tests. Now that's a pretty impressive reduction in loc

**Comment by pokey** [comment]
And looks like I missed a couple branch tests. Now all Python branch tests have been migrated. Have one more look when you get a minute and merge if you're happy

**Review by AndreasArvidsson — APPROVED** [review]

**Comment by pokey** [comment]
> Nice. First actual use of the scope recorder!
> 
> Easy to use? No problems?

Yep! Made a few tweaks as you saw, but otherwise quite usable. Definitely seems like a win

**Pull request merged**
