### PR TITLE
Html-item

### LINKED ISSUE #912: `touch item sun` inside jsx selects whole tag instead of attribute
Using this code `<Button data-testid="Action Button" data-variant="bare">`

CleanShot 2022-08-15 at 11 53 09

Say `touch key air`
CleanShot 2022-08-15 at 11 53 41
Selects `data-testid` as expected.

Say `touch value air`
CleanShot 2022-08-15 at 11 54 22
Also works as expected

Say `touch item air`
CleanShot 2022-08-15 at 11 55 10
Selects the whole contents of the JSX not `data-testid="Action Button"`

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #912

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — APPROVED** [review]
Nice. Any idea why this one now works?

**Comment by AndreasArvidsson** [comment]
No idea :D
But now the behavior is locked into the tests at least.

**Comment by auscompgeek** [comment]
I think it's because this isn't actually testing the issue. This is HTML whereas the issue uses JSX.

**Comment by AndreasArvidsson** [comment]
You are right! Then we do a second try #1601

**Pull request merged**
