### PR TITLE
Move types dependency to dev dependencies

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [/] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
@auscompgeek Any idea why there would be such a gigantic lockfile diff here?

**Comment by auscompgeek** [comment]
This diff does look pretty weird 🤔

**Comment by AndreasArvidsson** [comment]
Agreed. I was hoping one of you would have any ideas. The only thing I did was move the dependency and do a `pnpm install`.

**Comment by pokey** [comment]
very odd—when I did a pnpm install locally, I got a tiny diff. I pushed it here. Maybe something strange with your local pnpm @AndreasArvidsson?

**Review by auscompgeek — APPROVED** [review]

**Review by pokey — APPROVED** [review]

**Comment by AndreasArvidsson** [comment]
Could it be a version problem?
`7.30.1`

**Comment by auscompgeek** [comment]
That'd probably be it. Our corepack package manager version is pinned to an 8.x:
https://github.com/cursorless-dev/cursorless/blob/92b211223a8f493f201448ceeee848ad6c2ddcff/package.json#L56

**Comment by pokey** [comment]
Ah yeah you def want to be 8-series. They changed a bunch of stuff with v8

**Pull request merged**
