### PR TITLE
Include `@` in `name` for `scm` language

### PR DESCRIPTION
**Pull request by pokey**
Fixes https://github.com/cursorless-dev/cursorless/issues/1923

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Review by AndreasArvidsson — APPROVED** [review]
Looks good. By the way are we getting tired of manually having to disable all checkboxes for every pull request where they are not relevant?

**Comment by pokey** [comment]
> By the way are we getting tired of manually having to disable all checkboxes for every pull request where they are not relevant?

Of course 😄. Got any better ideas?

**Comment by AndreasArvidsson** [comment]
> > By the way are we getting tired of manually having to disable all checkboxes for every pull request where they are not relevant?
> 
> Of course 😄. Got any better ideas?
> 
> Tho to be clear, in this case I forgot 😅

Unfortunately not. I was just wondering because quite a few of your pull requests lately have had unfinished tasks. I would not be against revisiting if we actually need these if people anyhow just forget them. Unfortunately I can't really come up with a better solution.

**Comment by pokey** [comment]
I do think they are helpful. For example, I forgot to test the cheatsheet on the "access" PR until you mentioned the checkboxes here, and that PR very well could have broken the cheatsheet

Please feel free to nag me if I forget to check / scratch out the boxes 😊

**Pull request merged**
