### PR TITLE
cull trimRange

### PR DESCRIPTION
**Pull request by josharian**
It is unused. I believe that it also contains a latent bug,
when the range contains entirely whitespace.

Noticed during discussion at

https://github.com/cursorless-dev/cursorless/pull/1854#discussion_r1327290730

## Checklist

- [-] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [-] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [-] I have not broken the cheatsheet

### CODE REVIEW

**Comment by josharian** [comment]
Ping.

**Comment by josharian** [comment]
Ping.

**Comment by AndreasArvidsson** [comment]
Why not. Since we can always re-add it if we need it later.

**Review by AndreasArvidsson — APPROVED** [review]

**Comment by pokey** [comment]
Thanks @AndreasArvidsson. I recall looking at this PR, following the link to the original PR discussion that spawned it, getting stuck there, and that's the last thing I remember 😅. So I appreciate you taking action here 😄

**Pull request merged**
