### PR TITLE
Text edit based indent

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [/] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
update from meet-up: we'll get test coverage here once we have recorded tests running on talon js, so let's wait for test coverage in CI for talon js

**Comment by AndreasArvidsson** [comment]
@pokey This is now tested by the Talonjs recorded tests.

**Review by pokey — APPROVED** [review]
Looks good but for some reason I thought you already had indent and outdent in TalonJs and were planning to remove them as part of this PR. But maybe you already removed them?

**Comment by AndreasArvidsson** [comment]
> Looks good but for some reason I thought you already had indent and outdent in TalonJs and were planning to remove them as part of this PR. But maybe you already removed them?

I removed that before we merged the previous pull request.

**Pull request merged**
