### PR TITLE
Made interface names targetable as keys

### LINKED ISSUE #1790: Support for key in typescript interfaces
```ts
interface Hello {
    value: number
}
```
`value` here can be referred to as `name`, but not `key`. I would like to support both.
@pokey what do you think?

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #1790

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Review by auscompgeek — COMMENTED** [review]
Are type aliases handled already?

**Comment by AndreasArvidsson** [comment]
It is now!

**Review by auscompgeek — COMMENTED** [review]
What about object types in function signatures? 😅

**Comment by AndreasArvidsson** [comment]
It does now!!!

**Review by pokey — APPROVED** [review]

**Pull request merged**
