### PR TITLE
csharp migrate scopes

### PR DESCRIPTION
**Pull request by AndrewDant**
## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [x] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [x] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
Great start!

- [x] Be sure to add a domain so that it works from anywhere in the class
- [ ] Use the scm formatter from @AndreasArvidsson 's vscode extension for consistent formatting

**Review by AndrewDant — COMMENTED** [review]
> Great start!

> - [ ] Be sure to add a domain so that it works from anywhere in the class
- [ ] Use the scm formatter from @AndreasArvidsson 's vscode extension for consistent formatting 

Looks like I just need to manually save the file for the formatter to work, so that's easy enough. I don't know what you mean about the domain though, not seeing anything on the tree sitter parsers page about it.

**Comment by AndreasArvidsson** [comment]
> > Great start!
> 
> > * [ ]  Be sure to add a domain so that it works from anywhere in the class
> 
>     * [ ]  Use the scm formatter from @AndreasArvidsson 's vscode extension for consistent formatting
> 
> 
> Looks like I just need to manually save the file for the formatter to work, so that's easy enough. I don't know what you mean about the domain though, not seeing anything on the tree sitter parsers page about it.

Domain is a Cursorless concept. It tells Cursorless within which range this scope is valid. 
Look here. We have defined a key and a value and the domain for which these are valid.
https://github.com/cursorless-dev/cursorless/blob/2b6475e7305d46ee31f8eb374720791c03da6b0b/queries/javascript.core.scm#L641-L644

**Review by AndrewDant — COMMENTED** [review]
> >  don't know what you mean about the domain though, not seeing anything on the tree sitter parsers page about it.

Domain is a Cursorless concept. It tells Cursorless within which range this scope is valid. 
Look here. We have defined a key and a value and the domain for which these are applicable.
https://github.com/cursorless-dev/cursorless/blob/2b6475e7305d46ee31f8eb374720791c03da6b0b/queries/javascript.core.scm#L641-L644

`@_.domain` means this domain applies for all scopes within the pattern. You can also write `@value.domain` to specify the domain of a single scope within the pattern.
 

I'm not sure that I understand this example but I'll ask for clarification in the call today.

**Review by pokey — APPROVED** [review]
Looks good! Lmk if you're not sure how to fix CI; hopefully the error message makes sense. If not we can try to make it clearer

**Comment by AndrewDant** [comment]
@pokey I am planning on migrating more scopes, but I'll be away for five of the next seven days so it might be best to merge this one as is and start a new pull request next week, if this currently looks good.

**Comment by pokey** [comment]
let's ship it!

**Pull request merged**
