### PR TITLE
Added reformat action to public api

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [/] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [x] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [x] I have not broken the cheatsheet

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
Nice! I don't think we need tests, because the talon action is already tested

- [x] Would be good to add an example to the docs of how to use it in a command which takes a formatter via spoken form

**Comment by AndreasArvidsson** [comment]
> Nice! I don't think we need tests, because the talon action is already tested
> 
>     * [ ]  Would be good to add an example to the docs of how to use it in a command which takes a formatter via spoken form

I was planning to do that, but I can't find anywhere in our documentation where we have "recipes". Where should I place this?

**Comment by AndreasArvidsson** [comment]
@pokey I don't like that precommit removes trailing whitespaces from markdown files. I prefer to have it as two separate lines.

**Review by pokey — APPROVED** [review]

**Comment by auscompgeek** [comment]
> I don't like that precommit removes trailing whitespaces from markdown files. I prefer to have it as two separate lines.

You can use a backslash to hard line break in Markdown: https://spec.commonmark.org/0.31.2/#hard-line-breaks

**Comment by pokey** [comment]
> @pokey I don't like that precommit removes trailing whitespaces from markdown files. I prefer to have it as two separate lines.

Sorry I'm not following. Why do you want the trailing whitespace?

**Comment by pokey** [comment]
Ah right I wasn't familiar with that syntax. And yeah I'd def go for the backslash if you want a hard line break.

Although I'll generally always just go for two new lines to give a paragraph break. Eg that's what I would have done here

**Comment by AndreasArvidsson** [comment]
I've always used the syntax with trailing whitespaces for new lines, but of course since it's markdown you can do everything multiple ways :p

**Pull request merged**
