### PR TITLE
Run the check-line-endings script in GHA

### PR DESCRIPTION
**Pull request by auscompgeek**
Opening this to see what happens on Windows. I'm not convinced this script won't break dev workflows if this is run in pre-commit, so it should be tested cross-platform.

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
those CI failures are because it expects to be run with a list of paths, eg `bash ./scripts/check-line-endings.sh foo.js bar/baz.txt`

**Comment by pokey** [comment]
also, you'll get feedback a bit faster if you put it earlier in the action 😅

**Comment by auscompgeek** [comment]
Huh, `**` isn't a thing in bash?

**Comment by pokey** [comment]
huh i thought it was 🤔

**Comment by pokey** [comment]
ok well there's your windows failure.  strange, though; not the failure I would have anticipated

**Comment by auscompgeek** [comment]
I believe `pre-commit` runs in the worktree, but we can check its behaviour too

**Comment by pokey** [comment]
huh ok fair enough.  so I guess with their lint rule, it would still fail, but it would fix them?

**Comment by auscompgeek** [comment]
I guess... but given we have tests that depend on the line endings being correct we should probably set the line endings for those particular file types in `.gitattributes` so it's not an issue in the first place

**Comment by pokey** [comment]
> given we have tests that depend on the line endings being correct

That's actually not the case.  See https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/packages/cursorless-vscode-e2e/src/suite/testCaseRecorder.test.ts#L162-L164

> and we have otherwise conflicting settings with git defaults:
> 
> https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/.editorconfig#L6
> 
> https://github.com/cursorless-dev/cursorless/blob/68ba545520829a21e26d70437c650fb615d73344/.vscode/settings.json#L23
> 
> we should probably set the line endings for particular file types in `.gitattributes` so it's not an issue in the first place

That was the [original approach](https://github.com/cursorless-dev/cursorless/compare/main...4f6f182210a1190ed7976d2b24d86bcf243338b0), but we moved away from that for two reasons:

1. Maintaining the list of text file types was cumbersome and added complexity
2. We didn't want to force Windows users to check files out with LF if they really wanted to use CRLF smudging.  Though maybe the original approach actually would work ok with such a setup?

**Comment by pokey** [comment]
Closing in favour of https://github.com/cursorless-dev/cursorless/pull/1348

**Pull request closed without merging**
