### PR TITLE
Find VSCode settings in $XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by auscompgeek**
This change makes the VSCode settings.json search on par with VSCode itself on Linux, where the `$XDG_CONFIG_HOME` is respected.

This also cleans up the surrounding code a bit to match, appropriately using pathlib's features.

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet_html)

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
Nice.  I can confirm this works for me on MacOS.  @auscompgeek what platforms have you tested this on?  Given our lack of tests for Talon side, it would be good to manually test this on Windows, Linux and MacOS

**Comment by AndreasArvidsson** [comment]
Works fine on windows

**Review by AndreasArvidsson — APPROVED** [review]

**Comment by pokey** [comment]
Ok @auscompgeek assuming you've tested this on Linux I'm happy to merge

**Comment by auscompgeek** [comment]
Yep, tested on Linux both with and without $XDG_CONFIG_HOME set.

**Review by pokey — APPROVED** [review]
👌

**Pull request merged**
