### PR TITLE
Only focus editor if needed

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
* Saves performance/faster testing
* Mitigates #819 if the correct editor is already focused

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)

### CODE REVIEW

**Review by pokey — CHANGES_REQUESTED** [review]
This breaks the ability to select something in an editor (and focus it) when you have the terminal focused.  `activeEditor === editor` doesn't mean that the correct editor is _focused_, just that it is the active editor.  In VSCode there is no way to determine whether it is actually focused

**Comment by AndreasArvidsson** [comment]
Ah that is really unfortunate. #819 is really problematic for me at the moment. I'm going to have the rethink this.

**Comment by pokey** [comment]
I believe this solution also won't work if you are in an opposite split.  

Could maybe iterate the [tab groups](https://code.visualstudio.com/api/references/vscode-api#TabGroup:~:text=tabGroups%3A%20TabGroups) and then look at uri's inside any [diff tab](https://code.visualstudio.com/api/references/vscode-api#Tab:~:text=%3A%20TabInputText%20%7C-,TabInputTextDiff,-%7C%20TabInputCustom%20%7C)?  Then you ask the tab group for its view column and focus it.  Idk maybe there's a cleaner solution but that might work

**Comment by pokey** [comment]
Keeping in mind the tab api's are relatively new so you'll need to some type gymnastics if we want to keep maintaining backwards compatibility for VSCode

**Pull request closed without merging**
