### PR TITLE
Added python global list to collection item definition

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)

### CODE REVIEW

**Comment by pokey** [comment]
How come this one is marked as draft PR?

**Comment by AndreasArvidsson** [comment]
No idea. Seems to be undeterministic if a created pr will be draft or review ready by default?

**Comment by auscompgeek** [comment]
Can't say I've ever seen that before, although Refined GitHub does always show separate buttons when opening a PR.

**Comment by pokey** [comment]
Strange. I've never seen that behaviour either

**Review by pokey — APPROVED** [review]

**Comment by AndreasArvidsson** [comment]
It happens to me from time to time. Now idea why

**Comment by pokey** [comment]
How do you open your pull requests?

**Comment by AndreasArvidsson** [comment]
Usually by pushing the branch first and then clicking pull request => new on GitHub

**Pull request merged**
