### PR TITLE
Empty commit to trigger deploy

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
fwiw you should be able to do this by finding the failed run in our [action run history](https://github.com/cursorless-dev/cursorless/actions/workflows/test.yml?query=branch%3Amain), clicking on it, and hitting re-run in the top right

**Comment by AndreasArvidsson** [comment]
> fwiw you should be able to do this by finding the failed run in our [action run history](https://github.com/cursorless-dev/cursorless/actions/workflows/test.yml?query=branch%3Amain), clicking on it, and hitting re-run in the top right

It didn't fail; it was marked as skipped for some reason. I tried to rerun it multiple times, but it was just skipped every time. Quite strange;

**Comment by pokey** [comment]
i mean the test run, not the deploy. see how the test run is failed in that link I sent. The deploy will skip if the test fails. If you re-run the test and it succeeds, then the deploy should go ahead

**Comment by AndreasArvidsson** [comment]
Ah of course. Thank you!

**Comment by auscompgeek** [comment]
We should work out why the tests are flaky 😅

**Comment by pokey** [comment]
> We should work out why the tests are flaky 😅

it's actually a fairly easy fix now that we have better abstractions over fs https://github.com/cursorless-dev/cursorless/issues/2538

**Pull request merged**
