### PR TITLE
Proper handing of raw strings in rust

### LINKED ISSUE #2678: rust raw string breaks scopes
If a [rust raw string](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals) (e.g. `r#"foobar"#`) is present anywhere in a rust file, cursorless scopes stop working with the error: `Cannot read properties of undefined (reading 'endPosition')`

### PR DESCRIPTION
**Pull request by AndreasArvidsson**
Fixes #2678

## Checklist

- [x] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [/] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [/] I have not broken the cheatsheet

### CODE REVIEW

**Review by auscompgeek — CHANGES_REQUESTED** [review]
Could we also have a test for more hashes, like `r##"hello"##`?

**Comment by AndreasArvidsson** [comment]
> Could we also have a test for more hashes, like `r##"hello"##`?

Oh that is valid? I did not add support for that.

**Comment by auscompgeek** [comment]
> Oh that is valid?

Per [the language reference](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals) (also linked in the issue), yes :)

**Comment by AndreasArvidsson** [comment]
> > Oh that is valid?
> 
> Per [the language reference](https://doc.rust-lang.org/reference/tokens.html#raw-string-literals) (also linked in the issue), yes :)

Tree sitter gives us no help here so all those different combinations with hashes and backslashes is something we need to solve with regex in that case.

**Comment by AndreasArvidsson** [comment]
Now we support multiple hashes :)

**Review by auscompgeek — APPROVED** [review]

**Review by pokey — APPROVED** [review]

**Pull request merged**
