### PR TITLE
Fix Black

### LINKED ISSUE #1909: Black is not formatting anything
Since #1877, Black is no longer formatting cursorless-talon.

Manually running `black` on _any_ Python file, or even the entire directory, outputs:

```console
> black cursorless-talon
No Python files are present to be formatted. Nothing to do 😴
```

Commenting out this line makes Black work as expected again:

https://github.com/cursorless-dev/cursorless/blob/7369ceaa0dadb877549e328b518ad29f996e4513/pyproject.toml#L3

```console
> black cursorless-talon
All done! ✨ 🍰 ✨
59 files left unchanged.
```

### PR DESCRIPTION
**Pull request by auscompgeek**
Fixes #1909

### CODE REVIEW

**Comment by auscompgeek** [comment]
😕 do we intentionally have invalid Python syntax in that playground file?

https://github.com/cursorless-dev/cursorless/blob/7369ceaa0dadb877549e328b518ad29f996e4513/data/playground/python/values.py#L29

**Comment by pokey** [comment]
I don't think it's necessarily a bad thing to have bad syntax in the playground

**Review by pokey — COMMENTED** [review]
Is there not a way to make the exclusion work?

**Comment by auscompgeek** [comment]
I don't know, it was 1am my time and I just wanted to get black working again

**Review by pokey — APPROVED** [review]
Ok looks like `force-exclude` was supposed to be a regex. It's strange that there was no error thrown, just silently failing to format any files 🤔

**Comment by auscompgeek** [comment]
That's… quite amazing. Possibly worth filing an issue, but we should update black first.

**Comment by auscompgeek** [comment]
Wait, I was running black on the command line wasn't I 😅

**Comment by pokey** [comment]
> Wait, I was running black on the command line wasn't I 😅

yes, appears so, why?

**Pull request merged**
