### PR TITLE
refactor: make the text editor edit() interface better for neovim

### PR DESCRIPTION
**Pull request by saidelike**
## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

` 7189 passing (5m)` all tests passing.

Just marking it as a draft PR for now until I confirm from neovim side that this is good interface.

### CODE REVIEW

**Review by pokey — COMMENTED** [review]
This looks good to me but I wanted to get a quick look from @AndreasArvidsson, given I'm a bit too close to this one 😅

some background @AndreasArvidsson: for implementing neovim ide, it was quite awkward to make it look like the VSCode setup. This api seems a lot simpler to me

**Comment by saidelike** [comment]
@AndreasArvidsson the neovim implementation if you want to compare https://github.com/saidelike/cursorless/blob/e2ba46849bb700e1609d3b02b84dfdeb0d9f6e8a/packages/cursorless-neovim/src/ide/neovim/NeovimEdit.ts

**Comment by pokey** [comment]
@saidelike is this one good to merge? I think you were waiting to see whether this ended up being a good api for you to use for neovim

**Comment by saidelike** [comment]
yes, I validated the interface. It is ready to be merged

**Review by AndreasArvidsson — APPROVED** [review]

**Pull request merged**
