### PR TITLE
Add `implicit` special target

### PR DESCRIPTION
**Pull request by pokey**
- Depends on https://github.com/cursorless-dev/cursorless/pull/2170

## Checklist

- [ ] I have added [tests](https://www.cursorless.org/docs/contributing/test-case-recorder/)
- [ ] I have updated the [docs](https://github.com/cursorless-dev/cursorless/tree/main/docs) and [cheatsheet](https://github.com/cursorless-dev/cursorless/tree/main/cursorless-talon/src/cheatsheet)
- [ ] I have not broken the cheatsheet

### CODE REVIEW

**Comment by pokey** [comment]
There is a bit of a gotcha here:

A common use case might be `"from air and bat swap key with value"`, which is equivalent a cursorless version of `"take air and bat swap key with value"`. So the user will get in the habit of thinking of `"from air <action> key"` as equivalent to `"<action> key air"`

So the user might expect to be able to say `"from air take every instance key"`, and have it be equivalent to `"take every instance key air"`. But that's not the case, because when you use `"instance"`, the `"from"` action is setting the range in which to search for instances, so it would try to search in the token `"air"` for the `"key"` containing the cursor

cc/ @AndreasArvidsson https://github.com/cursorless-dev/cursorless/labels/to%20discuss

**Comment by pokey** [comment]
update from meet-up: planning to try just using "take" to break up commands, so maybe this one isn't necessary. Only problem is we lose rich semantics. But let's try for a while

**Comment by pokey** [comment]
update: I had a long one I wanted to break up: `"carve next sub three views first three subs gust"`. Slight annoyance that when breaking this up with "take", I need to do

1. "take first three subs gust"
2. "take three views _sub_" (because I lost the "sub" from the first command)
3. "carve next sub"

**Comment by AndreasArvidsson** [comment]
That is an intriguing idea

**Comment by josharian** [comment]
Interesting. I definitely see the appeal, but I am a little nervous about hidden state. It can make a system hard to reason about as a user. (For a very wordy example, see https://commaok.xyz/post/fork-point/.)

**Comment by pokey** [comment]
Fwiw it wouldn't be hidden. We'd show the highlight

**Comment by josharian** [comment]
Ahhh. In that case, concern withdrawn.

**Comment by pokey** [comment]
closing for now as it's not clear we'll move in this direction. for now, let's just try to get in the habit of saying "take"

**Pull request closed without merging**
